kleyv/airbnb-falcony

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/puma.rb
- config/routes.rb
- db/migrate/20200824153941_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
I added the user model using the devise gem to create the default
values.
> Add devise user model

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/puma.rb
- config/routes.rb
- db/migrate/20200824153941_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
Reverts kleyv/airbnb-falcony#2
> Revert "Revert "Add devise user model""

- app/models/bookmark.rb
- app/models/funding.rb
- app/models/project.rb
- app/models/user.rb
- db/migrate/20200824164244_create_projects.rb
- db/migrate/20200824173424_create_fundings.rb
- db/migrate/20200824175320_create_bookmarks.rb
- db/schema.rb
- test/models/bookmark_test.rb
- test/models/funding_test.rb
- test/models/project_test.rb
Generate model - with corresponding migration and connection of
foreign_keys
Also added validations
Be careful - dependent on which connection either user_id equals
to investor_id or owner_id
> Generated models project & funding & bookmark

- docs/database_blueprint.md
I added a docs folder that we can use important info about the app,
the tools we use to create it and relevant steps. I started by
creating a blueprint of our database with the
database_blueprint.md file.
> Add docs folder and database_blueprint.md

- docs/github_guides.md
I added the file to describe morning routine
> Add github_guides.md

- app/models/project.rb
Added project.rb - dependent destroy
> Changed dependent destroy on models

- db/migrate/20200824164244_create_projects.rb
- db/migrate/20200824173424_create_fundings.rb
t.boolean “accepted”
must be t.boolean “accepted?”
t.integer “total_share”
must be t.integer “total_shares”
t.string “status”
must be t.boolean “open?”
> Correct some type in schema

- db/schema.rb
I updated the schema.rb file with the changes made by @raffoz
because it hadn't been push correctly to master.
> Update changes to schema.rb

- app/controllers/bookmarks_controller.rb
- app/controllers/fundings_controller.rb
- app/controllers/projects_controller.rb
- app/views/projects/index.html.erb
- test/controllers/bookmarks_controller_test.rb
- test/controllers/fundings_controller_test.rb
- test/controllers/projects_controller_test.rb
1. Added the fundings, projects and bookmarks controllers
2. Added index page with some filters for owner
> Added index page and some controllers

- Gemfile
- Gemfile.lock
- app/models/project.rb
- db/seeds.rb
I changed the validations on project.rb to reflect the changes
from total_share to total_shares.
I installed 'faker' to generate the seeds and generated 5 owners,
5 investors, 5 projects, 5 fundings and 5 bookmarks.
> Create seeds for the database

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- test/controllers/pages_controller_test.rb
We tuned all together this stuff
> Tuned devise and pages/home and navbar

- app/controllers/fundings_controller.rb
- app/controllers/projects_controller.rb
- app/views/fundings/index.html.erb
- app/views/projects/show.html.erb
- config/routes.rb
We created routes for the funding model,
the methods for projects and fundings and
the index page for fundings.
> Add ability to create offers to projects

- app/controllers/projects_controller.rb
- app/views/projects/new.html.erb
- config/routes.rb
Forms done, but i think the routing needs to be done from index, for it to work.
changed:
- routes file
- project controller
created:
-new.html.erb
> Add new page

- app/models/funding.rb
> changed range validation for funding_shares

- db/seeds.rb
I changed the algorithm to have more investors and so that each
investor can have more than one investment and bookmark per
project.
> Improve seeds to have more investments per investor

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/projects/new.html.erb
- db/seeds.rb
-added the categories array
-changed the label for total_funding
-added a validates to the project model
> Redone the new project form

- app/controllers/fundings_controller.rb
- app/controllers/projects_controller.rb
- app/models/funding.rb
- app/models/project.rb
- app/views/projects/show.html.erb
- config/routes.rb
- db/migrate/20200824164244_create_projects.rb
- db/migrate/20200824173424_create_fundings.rb
- db/schema.rb
- db/seeds.rb
- Updated show page dependent on owner or investor
- Updated database migrations
- Updated controller - projects and fundings
- Updated routes - added post request for link on show page to
redirect to projects controller accept
> Added accept logic for funding for owners and show page

- app/controllers/projects_controller.rb
- app/views/projects/index.html.erb
- app/views/projects/personal.html.erb
- app/views/projects/show.html.erb
- config/routes.rb
Links on index, personal and show pages (projects controller)
> Add edit-destroy features

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/projects/edit.html.erb
- app/views/projects/new.html.erb
- app/views/projects/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20200827100024_create_active_storage_tables.active_storage.rb
- db/migrate/20200827102701_add_description_to_projects.rb
- db/schema.rb
addedd cloudinary set up with env. file
added dotenv gem and cloudinary gem
set up active storage
added photo upload to new project and edit project
added description to project model and new/edit
> Changed backend of project model

- app/views/shared/_navbar.html.erb
- config/routes.rb
I added a non-nested route for fundings#index at '/fundings' and
added a link on the navbar to it.
I also deleted a an empty /soresi folder that was added somewhere
along the way.
> Add a link to all the fundings of current investor

- app/views/projects/show.html.erb
- db/seeds.rb
with pics and description and default share percentage of 100
> created ten new projects in seed file

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_projects.scss
- app/views/projects/show.html.erb
- app/views/shared/_footer.html.erb
Also changed body margin, to make some space after navbar
> Design of home page

- db/seeds.rb
I added two static users to every seed so we always have test
accounts from the seed. I also changed the password for the
dynamic seed to always be 'password'.
> Add owner and investor test users

- app/views/fundings/index.html.erb
I added some simple bootstrap to make the text pop and added
links to each project.
> Design fundings index page

- app/assets/stylesheets/pages/_projects.scss
- app/views/projects/show.html.erb
Show page for owner still needs to be updated after lunch!!!
> updated first part of show page - for investor.

- app/assets/stylesheets/components/sign-up-btn.scss
- app/assets/stylesheets/pages/_formsdevice.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_log_in_layout.scss
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/log_in_layout.html.erb
added back buttons, background picture
> Changed sign up forms style

- app/controllers/bookmarks_controller.rb
- app/controllers/fundings_controller.rb
- app/controllers/projects_controller.rb
I changed the order by which items are displayed so we always
have the latest one at the top.
> Order the projects, fundings and bookmarks by created_at

- app/controllers/fundings_controller.rb
- app/controllers/projects_controller.rb
We changed the fundings and projects controllers to so that
the validations passed.
> Fix adding funding as an investor

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_fundings.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_project_new.scss
- app/assets/stylesheets/pages/_project_show.scss
- app/assets/stylesheets/pages/_projects.scss
- app/views/bookmarks/index.html.erb
- app/views/fundings/index.html.erb
- app/views/layouts/application.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/index.html.erb
- app/views/projects/new.html.erb
- app/views/projects/personal.html.erb
- app/views/projects/show.html.erb
- app/views/shared/_footer.html.erb
Finished:
- fundings page
- project#show
- rewritten all html.erb code in show page: now it's clean and readable
- footer now works perfect
Still need to finish login and signu pages.
> Worked on website

- app/assets/stylesheets/pages/_formsdevice.scss
I  changed the where the background image so it would fill all
of the view.
> Move session form background image to the body element

- app/assets/stylesheets/pages/_formsdevice.scss
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Using body in taht file affects all other bodies of all pages.
The <body> in that scss is not referred just to that views.
It's just a name thing, but when you set body in some scss files, it applies to ALL pages.
> Fixed bg in _formsdevise.scss

- app/assets/stylesheets/pages/_formsdevice.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_project_new.scss
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
- app/views/projects/index.html.erb
- app/views/projects/personal.html.erb
- app/views/shared/_navbar.html.erb
A lot of small css changes in everypage
Very strange behavior: navbar must be rendered in device pages to be shown
> Tuned everything
